apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-iotdb.fullname" . }}
  labels:
    {{- include "apache-iotdb.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6667
      name: iotdb-external
  selector:
    {{- include "apache-iotdb.selectorLabels" . | nindent 4 }}
  type: LoadBalancer

