apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-iotdb.fullname" . }}-headless
  labels:
    {{- include "apache-iotdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 6667
      name: iotdb-external
  selector:
    {{- include "apache-iotdb.selectorLabels" . | nindent 4 }}

